### ISSUE TITLE
[resource] utilize libram summons

### ISSUE THREAD

**Issue by docrostov** [Loathing-Associates-Scripting-Society/garbage-collector#199]
garbo should probably try to do minimum-viable-product libram summoning; if you call breakfast before/after garbo you will get some libram summons per your internal mafia preferences but libram stuff can be some decent extra meat depending on how much MP you can generate freely/cheaply, and garbo does generate a lot of "spare" MP. as with tome summons, this could be immensely complicated or super simple, just depends on your goals and usage parameters.

**Comment by Rinn** [comment]
Limited rares
- Bricko: 50% for first eye brick (+2 brick), 33% for second and third, max of _brickoEyeSummons=3
- Taffy: 50% / (_taffyRareSummons+1), max of _taffyYellowSummons=1 and _taffyRareSummons=4
Unlimited
- Bricko: 100% 3x Bricko Brick
- Candy Hearts: equal chance
- Party Favors: 50% / (_favorRareSummons+1) chance of any rare, no lower limit, equal cahnc
- Love songs: equal chance of any
- Dice: equal chance of any
- Resolutions: 2% chance of any rare
- Taffy: equal chance 
Maybe if the estimated price is below some threshold it rotates through the librams just for more variety. Mafia doesn't track the number of times each libram has been cast individually though.

Imo i'd maybe just prioritize getting all the limited rares first since garbo fights brickos and uses a green taffy copy if you have robort.

**Comment by Rinn** [comment]
It might be better if libram had a function that returned an array of expected result chance for a summon

**Comment by horrible-little-slime** [comment]
This is not fully closed, but it can be soon; thanks to @Rinn's libram support in libram, we now burn MP before using PYEC and LTC, and can expand that code to other places.

**Comment by horrible-little-slime** [comment]
Closing this as an issue; it'd be neat to milk more out of it, but we don't have to.
