### ISSUE TITLE
Feature Request: Unified Log

### ISSUE THREAD

**Issue by pstalcup** [Loathing-Associates-Scripting-Society/garbage-collector#258]
We should have a property or file that can contain lots of information about the current session, to be printed at the end of a successful run, e.g.

* How many KGE we fought
* How many digitized combats we did
* What our average MPA was (Both considering and not KGE)
* What Guzzlr quests we did
* How many turns until the guzzlr quest is complete
* etc.

**Comment by pstalcup** [comment]
I am willing to undertake writing this, but I would like a little direction for how we want to architect (if its something that is useful at all)

**Comment by horrible-little-slime** [comment]
I think rather than a map as you suggested in discord I would make some object in the global scope like

```
export const log = {
  kge: 0,
  digitizes: 0,
  guzzlrPlats: 0,
  guzzlrGolds: 0,
  guzzlrBronzes: 0,
  ... etc
}
```
and modify those properties as you go. Finding average MPA strikes me as difficult because you can't just snapshot how much meat you had at the start and at the end, and I wouldn't want to update totalMeat every turn because that seems bad. Maybe it isn't bad, though!
