### ISSUE TITLE
Vote, and fight free voter wanderers while farming

### ISSUE THREAD

**Issue by Phillammon** [Loathing-Associates-Scripting-Society/garbage-collector#30]
Split off from #23

**Comment by Malibu-Stacey** [comment]
The first part I do in ASH using the following

```
    if (get_property("_voteModifier") == "") {
      cli_execute("VotingBooth");
    }
```
You'll want to add https://github.com/Ezandora/Voting-Booth as a dependency to make that work. Otherwise you'll need to write handling for the voting booth yourself.

The second part I do in ASH using the following:

`set_property("trackVoteMonster", "free");`

```
    if (get_counters("Vote Monster", 0, 0).contains_text("Vote Monster")) {
      // do outfit and zone selection here. Remember to equip the vote sticker.
      adv1($location[noob cave], -1, "");
    }
```

You need the property set for the counter to be added.

**Comment by Phillammon** [comment]
Yyyup, that matches my plan, give or take. I'm thinking rather than using counters, perform the check manually in meatoutfit to determine whether we equip sticker or not.
