### ISSUE TITLE
Improve familiar prioritisation

### ISSUE THREAD

**Issue by Phillammon** [Loathing-Associates-Scripting-Society/garbage-collector#39]

**Comment by docrostov** [comment]
here are some basic high level ideas for familiar prioritization

- when in doubt, fist turkey is great. the booze sells for a pretty high mark and the drop rates on the first 3 are relatively good. also, it has some % chance of digging up meat after the first round, which at high fam weight adds something like 1-2k in any fight it procs.
- getting thesis XP is always good until that xp has been resolved, this is probably highest priority.
- doing a lookup on value for familiars that drop things is kind of a pain but might be valuable, a -lot- of familiars drop a ton of nonsense
- without full stasis support, don't think stocking mimic is really worth it. i would probably go with fist turkey for every fight before i did a mimic tbh lol. one way to sidestep familiar concerns would be to implement stasis support, but to me that feels like doing a ton of work to avoid doing another form of work, so it's kind of a pick-your-poison thing.

here is a possibly incomplete list of fams that drop things relevant to a farming script:

- robortender (so much nonsense; 100% rate on first fight, decays to ~ 10%. my old script spent freekills in HitS for robort ingredients tbh. melange is probably better but might not be!)
- fist turkey (ambitious turkey, 4 fights increasing with each drop; limit 5)
- golden monkey (powdered gold, 3 fights increasing with each drop)
- galloping grill (hot ash, wiki unclear on rate; limit 5) 
- machine elf (abstractions, every few fights)
- puck man (i am not going to pretend to understand how puck man works)
- rockin' robin (robin's egg, 30 turn counter w/ quicker first drop)
- garbage fire (flaming newspaper, 30 turn counter w/ quicker first drop)
- optimistic candle (glob of melted wax, 30 turn counter w/ quicker first drop)
- adventurous spelunker (tales of spelunking, 13 fights; limit 1)
- mechanical songbird (clockwork egg, 150 fights)
- grimstone golem (grimstone mask, 45 fights; limit 1)

**Comment by horrible-little-slime** [comment]
For scotch's edification, the puck-man drops two things: yellow pixels, and power pills. The number of power pills it drops per day is Math.min(11, myDaycount() + 1), and those each take 10-20 combats. Without equipment, it drops 1 yellow pixel per combat. With equipment, it occasionally drops 2, at a rate I can't find.

For meat familiars, if a player doesn't have a hobo monkey (or cactus bud, or bort), would it be worth iterating over Familiar.all() and picking something spicier than a base leprechaun? We could prioritize drop familiars, followed by fairychauns, and then default to leprechaun. This feels like it has a pretty small target audience though, because you need to have an iotm familiar but not a hobo monkey, and also have whatever minimal set of things you need to be running garbo.
