### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by pstalcup** [Loathing-Associates-Scripting-Society/garbage-collector#716]
After some discussion in the discord, it seems like there is a general consensus that we should move all settings details into a new file to manage them

Goals:
* Have a function that gets run on startup that processes all preferences and string arguments to build out what the run settings for garbo are
* Create consistent documentation for each setting that can be automatically pulled from to generate the Help documentation as well as the relay page

Future goals:
* Create some sort of automation setting that disables all uses of User Confirms
* Each run setting could have a corresponding preference so that invoking garbo can be as simple as "garbo"
* Create ability to export and import settings, and possibly have tools to generate default settings for new users

**Comment by pstalcup** [comment]
I am mostly just looking for some thoughts on this before I go ahead and add settings.ts
Is there anything in particular that we should cover?
At some point I would like to refer to the source code to automatically generate some of the markdown documentation, but I am not really sure how to do that

**Comment by horrible-little-slime** [comment]
I am a little concerned about the scale of scope creep this could create, but largely in support of it.

**Comment by docrostov** [comment]
i am wholeheartedly in support of this as it will help headless users and let people at least slightly modify garbo actions per their goals and requests. a few things i think we should think about:

- do we want to make settings that are path dependent? IE, do X if in CS, do Y if not in CS. this feels much closer to the scope creep problem phred said so i am not necessarily in support of this but we should think about it.
- the discussion yesterday in garbo basically boiled down to "i use garbo in a very weird way because i want to track my data in a funny way we didn't expect." to phred's point, as we add settings we need to figure out ways to make sure we aren't creating weird intersections of settings that lead to negative behaviors that we never tested. in the service of this, i think we should make a rule that after we make a simple first pass of settings, we require that new settings are tested in multiple days of garbo with different configs before pushed to main. feel free to push back on this, that's just my view on it.
- to phred's point about eventually having a relay version, we should make sure the settings names are relatively compact and easy to explain bc we may eventually expose these to the user in a relay form.

**Comment by horrible-little-slime** [comment]
My answer to most people saying that they use garbo in a very weird way
that no one expects is not to do that; I think it is dangerous to start
assigning development time and energy for weird use cases like that.

At the same time, I am in support of having a wider array of settings. The
big one I've been looking at is workshed swaps. I feel like you should have
to very deliberately turn that on, but also it would be great to have!

**Comment by pstalcup** [comment]
What i am imagining is that a power user who wants to switch garbo settings between paths (say between loops) would control it manually via a "garbo settings export <name>" and "garbo settings import <name>" 

If data tracking is an issue, I would approve of a heavier logging capability. One option (this is probably a dumb one, but worth considering) adding a "loggingScript" hook that could be triggered with heaps of garbo data so that anyone could hook into that to track whatever they want

For the relay version - I am hoping that we can share code between this file and the relay script to cut down on any naming issues.

**Comment by horrible-little-slime** [comment]
So we would have a big ol' JSON Bourne that this reads and writes to?

**Comment by docrostov** [comment]
> My answer to most people saying that they use garbo in a very weird way that no one expects is not to do that; I think it is dangerous to start assigning development time and energy for weird use cases like that. At the same time, I am in support of having a wider array of settings. The big one I've been looking at is workshed swaps. I feel like you should have to very deliberately turn that on, but also it would be great to have!

so my point on that is less "we need to expect weird ways" and more "we need to make sure we aren't accidentally baking those weird ways into garbo". for instance, the specific case yesterday (of running garbo nobarf then garbo barf separately and diet being nontrivially different between those two cases) feels like a weird thing we shouldn't support, but if we were to somehow create an interaction of features that segregated the diet code between loops such that it figures out barf or nobarf given your available turns in your final casual leg, it could've caused a weird issue similar to that in nature. i don't know if i'm explaining this right but my point is more just "we probably should have a few multis ready to go for garbo testing explicitly and for testing weird settings constructions"

**Comment by horrible-little-slime** [comment]
Should this be closed now that grimoire args are live?

**Comment by docrostov** [comment]
> 

yes, and i will close it
